# Generated by Django 3.1.4 on 2025-06-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20250610_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoc',
            name='cmptype',
            field=models.CharField(blank=True, choices=[('Deduction', 'Contract'), ('Earning', 'Earning')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='payactionstatus',
            name='actiontype',
            field=models.CharField(blank=True, choices=[('Pay', 'Pay'), ('On Hold', 'On Hold')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emptype',
            field=models.CharField(blank=True, choices=[('Contract', 'Contract'), ('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Intern', 'Intern')], max_length=40, null=True),
        ),
    ]
