# Generated by Django 3.1.4 on 2025-06-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20250610_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoc',
            name='cmptype',
            field=models.CharField(blank=True, choices=[('Earning', 'Earning'), ('Deduction', 'Contract')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='payoutstatus',
            name='reason',
            field=models.CharField(blank=True, choices=[('Pay', 'Pay'), ('Unpaid', 'Unpaid')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='payoutstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('Pay', 'Pay'), ('Unpaid', 'Unpaid')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reportingmanager',
            name='type',
            field=models.CharField(blank=True, choices=[('Secondary', 'Secondary'), ('Primary', 'Primary')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emptype',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], max_length=40, null=True),
        ),
    ]
