# Generated by Django 3.1.4 on 2025-06-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20250610_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoc',
            name='cmptype',
            field=models.CharField(blank=True, choices=[('Deduction', 'Contract'), ('Earning', 'Earning')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='payactionstatus',
            name='actiontype',
            field=models.CharField(blank=True, choices=[('On Hold', 'On Hold'), ('Pay', 'Pay')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reportingmanager',
            name='type',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emptype',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Intern', 'Intern'), ('Part Time', 'Part Time'), ('Contract', 'Contract')], max_length=40, null=True),
        ),
    ]
