# Generated by Django 3.1.4 on 2025-06-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20250610_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoc',
            name='cmptype',
            field=models.CharField(blank=True, choices=[('Earning', 'Earning'), ('Deduction', 'Contract')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='payactionstatus',
            name='actiontype',
            field=models.CharField(blank=True, choices=[('Pay', 'Pay'), ('On Hold', 'On Hold')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reportingmanager',
            name='type',
            field=models.CharField(blank=True, choices=[('Secondary', 'Secondary'), ('Primary', 'Primary')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emptype',
            field=models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Full Time', 'Full Time'), ('Contract', 'Contract'), ('Part Time', 'Part Time')], max_length=40, null=True),
        ),
    ]
