# Generated by Django 3.1.4 on 2025-06-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20250613_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payactionstatus',
            name='actiontype',
            field=models.CharField(blank=True, choices=[('Pay', 'Pay'), ('On Hold', 'On Hold')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='payoutstatus',
            name='reason',
            field=models.CharField(blank=True, choices=[('Pay', 'Pay'), ('Unpaid', 'Unpaid')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='payoutstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('Pay', 'Pay'), ('Unpaid', 'Unpaid')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emptype',
            field=models.CharField(blank=True, choices=[('Contract', 'Contract'), ('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Intern', 'Intern')], max_length=40, null=True),
        ),
    ]
