from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from app1 import views
from app1.routing import websocket_urlpatterns
import execute  # don't remove this

urlpatterns = [
    path('admin/', admin.site.urls),

    # path('',views.adminlogin,name='login'),
    path('sign_up', views.sign_up, name='sign_up'),
    path('', views.loginf, name='login'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('dashboard<int:id>', views.dashboard_search, name='dashboardsearch'),
    path('empdetails<int:id>', views.view_emp, name='viewemp'),
    # path('empteamdetails<int:id>',views.view_empteam,name='viewempteam'),
    path('empworkdetails<int:id>', views.view_empwork, name='viewempwork'),
    path('empedudetails<int:id>', views.view_empedu_details, name='viewempedu'),
    path('empfamdetails<int:id>', views.view_empfam_details, name='viewempfam'),
    path('empdocdetails<int:id>', views.view_empdoc_details, name='viewempdoc'),
    path('employee<int:id>', views.employee_search, name='employeesearch'),
    path('emplodetails<int:id>', views.view_employee, name='viewemployee'),

    path('view_personalinfo<int:id>',
         views.view_personalinfo, name='view_personalinfo'),
    path('admin_create_personalinfo<int:id>',
         views.admin_create_personalinfo, name='admin_create_personalinfo'),

    path('view_work<int:id>', views.view_work, name='view_work'),
    path('admin_create_empwork<int:id>',
         views.admin_create_empwork, name='admin_create_empwork'),

    path('view_team<int:id>', views.view_team, name='view_team'),

    path('adminadd_reportingmanager<int:id>',views.adminadd_reportingmanager, name='adminadd_reportingmanager'),
    path('admindelete_reportingmanager<int:id>',views.admindelete_reportingmanager, name='admindelete_reportingmanager'),

    path('view_education<int:id>', views.view_education, name='view_education'),
    path('admin_add_empeducation<int:uid_4>',
         views.admin_add_empeducation, name='admin_add_empeducation'),
    path('admin_edit_empeducation<int:id>',
         views.admin_edit_empeducation, name='admin_edit_empeducation'),
    path('admin_delete_empeducation<int:id>',
         views.admin_delete_empeducation, name='admin_delete_empeducation'),

    path('view_family<int:id>', views.view_family, name='view_family'),
    path('admin_add_empfamily<int:uid_5>',
         views.admin_add_empfamily, name='admin_add_empfamily'),
    path('admin_edit_empfamily<int:id>',
         views.admin_edit_empfamily, name='admin_edit_empfamily'),
    path('admin_delete_empfamily<int:id>',
         views.admin_delete_empfamily, name='admin_delete_empfamily'),
    path('admin_add_emergencycontact<int:uid_6>',
         views.admin_add_emergencycontact, name='admin_add_emergencycontact'),
    path('admin_edit_emergencycontact<int:id>',
         views.admin_edit_emergencycontact, name='admin_edit_emergencycontact'),
    path('admin_delete_emergencycontact<int:id>',
         views.admin_delete_emergencycontact, name='admin_delete_emergencycontact'),
     
    path('view_document<int:id>', views.view_document, name='view_document'),
    path('view_deletedocument<int:id>',views.view_deletedocument,name='view_deletedocument'),
    path('doc_verification<int:id>',
         views.doc_verification, name='doc_verification'),
    path('view_certification<int:id>',
         views.view_certification, name='view_certification'),
#     path(' view_deletecertification<int:cert_id>/<int:user_id>',views. view_deletecertification,name='view_deletecertification'),
    path('delete_certification<int:cert_id>', views.delete_certification, name='delete_certification'),

    path('cert_verification<int:id>',
         views.cert_verification, name='cert_verification'),
    path('view_docwork<int:id>', views.view_docwork, name='view_docwork'),
    path('view_workweek<int:id>', views.view_workweek, name='view_workweek'),
    path('view_payroll<int:id>', views.view_payroll, name='view_payroll'),
    path('view_salarystructure<int:id>',
         views.view_salarystructure, name='view_salarystructure'),
    path('view_declaration<int:id>',
         views.view_declaration, name='view_declaration'),

    path('view_bankaccount<int:id>',
         views.view_bankaccount, name='view_bankaccount'),
    path('admin_update_bankaccount<int:id>',
         views.admin_update_bankaccount, name='admin_update_bankaccount'),

    path('view_e_exit<int:id>', views.view_e_exit, name='view_e_exit'),
    path('view_filemanager<int:id>',
         views.view_filemanager, name='view_filemanager'),

    path('empdash', views.empdash, name='empdash'),
    path('resetpassword<int:id>', views.resetpassword, name='resetpassword'),

    path('employee', views.add_employee, name='add_employee'),
    path('update-employee<int:userid>',
         views.update_employee, name='update_employee'),
     path('update-inactive-employee<int:userid>',
         views.update_inactive_employee, name='update_inactive_employee'),
    path('directory', views.directory, name='directory'),
    path('inactive-users', views.list_inactive_employee, name="list_inactive_employee"),

    path('verify', views.verify, name='verify'),
    path('emp-directory', views.empdirectory, name='empdirectory'),
    path('delete_directory<int:userid>',
         views.delete_directory, name='delete_directory'),
    path('export_empdetails', views.export_empdetails, name='export_empdetails'),

    # MYPROFILE
    path('personalinfonav', views.personal_info_nav, name='personalinfonav'),
    path('emppersonalinfonav', views.emppersonal_info_nav,
         name='emppersonalinfonav'),
    path('createpersonalinfo', views.create_personal_info,
         name='createpersonalinfo'),
    path('empcreatepersonalinfo', views.empcreate_personal_info,
         name='empcreatepersonalinfo'),
    path('worknav', views.work_nav, name='worknav'),
    path('empworknav', views.empwork_nav, name='empworknav'),
    path('creatework<int:userid>', views.create_work, name='creatework'),
    path('empcreatework', views.empcreate_work, name='empcreatework'),
    path('tableworkhistory<int:uid_1>',
         views.table_work_history, name='tableworkhistory'),
    path('teamnav', views.team_nav, name='teamnav'),
    path('empteamnav', views.empteam_nav, name='empteamnav'),
    path('tablereportingmanager', views.table_reporting_manager,
         name='tablereportingmanager'),
    path('updatereportingmanager', views.update_reportingmanager,
         name='updatereportingmanager'),
    path('deletereportingmanager<int:r_id>',
         views.delete_reportingmanager, name='deletereportingmanager'),
    path('tabledirectreports', views.table_direct_reports,
         name='tabledirectreports'),
    path('update_directreports', views.update_directreports,
         name='updatedirectreports'),
    path('delete_directreports<int:myuser_3__id>',
         views.delete_directreport, name='deletedirectreports'),
    path('emptablereportingmanager<int:uid_2>',
         views.emptable_reporting_manager, name='emptablereportingmanager'),
    path('empupdatereportingmanager', views.empupdate_reportingmanager,
         name='empupdatereportingmanager'),
    path('empdeletereportingmanager<int:r_id>',
         views.empdelete_reportingmanager, name='empdeletereportingmanager'),
    path('emptabledirectreports<int:uid_3>',
         views.emptable_direct_reports, name='emptabledirectreports'),
    path('empupdate_directreports', views.empupdate_directreports,
         name='empupdatedirectreports'),
    path('empdelete_directreports<int:myuser_3__id>',
         views.empdelete_directreport, name='empdeletedirectreports'),
    path('educationnav', views.education_nav, name='educationnav'),
    path('empeducationnav', views.empeducation_nav, name='empeducationnav'),
    path('tableeduinfo<int:uid_4>', views.table_edu_info, name='tableeduinfo'),
    path('updateeduinfo', views.update_eduinfo, name='updateeduinfo'),
    path('deleteeduinfo<int:myuser_4__id>',
         views.delete_eduinfo, name='deleteeduinfo'),
    path('emptableeduinfo<int:uid_4>',
         views.emptable_edu_info, name='emptableeduinfo'),
    path('empupdateeduinfo', views.empupdate_eduinfo, name='empupdateeduinfo'),
    path('empdeleteeduinfo<int:myuser_4__id>',
         views.empdelete_eduinfo, name='empdeleteeduinfo'),
    path('familynav', views.family_nav, name='familynav'),
    path('empfamilynav', views.empfamily_nav, name='empfamilynav'),
    path('tablefammembers<int:uid_5>',
         views.table_fam_members, name='tablefammembers'),
    path('updatefammembers', views.update_fam_members, name='updatefammembers'),
    path('deletefammembers<int:myuser_5__id>',
         views.delete_fam_members, name='deletefammembers'),
    path('emptablefammembers<int:uid_5>',
         views.emptable_fam_members, name='emptablefammembers'),
    path('empupdatefammembers', views.empupdate_fam_members,
         name='empupdatefammembers'),
    path('empdeletefammembers<int:myuser_5__id>',
         views.empdelete_fam_members, name='empdeletefammembers'),
    path('tableemergencycontact<int:uid_6>',
         views.table_emergency_contact, name='tableemergencycontact'),
    path('updateemergencycontact', views.update_emergency_contact,
         name='updateemergencycontact'),
    path('deleteemergencycontact<int:myuser_6__id>',
         views.delete_emergency_contact, name='deleteemergencycontact'),
    path('emptableemergencycontact<int:uid_6>',
         views.emptable_emergency_contact, name='emptableemergencycontact'),
    path('empupdateemergencycontact', views.empupdate_emergency_contact,
         name='empupdateemergencycontact'),
    path('empdeleteemergencycontact<int:myuser_6__id>',
         views.empdelete_emergency_contact, name='empdeleteemergencycontact'),
    path('documentsnav', views.documents_nav, name='documentsnav'),
    path('delete_document/<int:doc_id>', views.delete_document, name='delete_document'),
    path('empdocumentsnav', views.empdocuments_nav, name='empdocumentsnav'),
    path('delete_emp_document/<int:doc_id>', views.delete_emp_document, name='delete_emp_document'),
    path('tableuploadeddocs<int:uid_7>',
         views.table_uploaded_docs, name='tableuploadeddocs'),
    path('update_docs',views.update_docs, name='update_docs'),
    path('emptableuploadeddocs<int:uid_7>',views.emptable_uploaded_docs, name='emptableuploadeddocs'),
    path('empupdate_docs',views.empupdate_docs, name='empupdate_docs'),
    path('updateuploadeddocs', views.update_uploaded_docs,
         name='updateuploadeddocs'),
    # path('deleteuploadeddocs<int:uid_7>',views.delete_uploaded_docs,name='deleteuploadeddocs'),
    path('certifications', views.certifications, name='certifications'),
#     path('delete_certifications/<int:cert_id>', views.delete_certifications, name='delete_certifications'),  
    path('edit_empcertifications', views.edit_empcertifications,name='edit_empcertifications'),
    path('edit_certifications', views.edit_certifications,name='edit_certifications'),
    path('delete_empcertifications/<int:cert_id>', views.delete_empcertifications, name='delete_empcertifications'),  
    path('tablecertifications<int:uid_8>',
         views.table_certifications, name='tablecertifications'),
    path('empcertifications', views.empcertifications, name='empcertifications'),
    path('emptablecertifications<int:uid_8>',
         views.emptable_certifications, name='emptablecertifications'),
    path('updatecertifications', views.update_certifications,
         name='updatecertifications'),
    # path('deletecertifications<int:uid_8>',views.delete_certifications,name='deletecertifications'),
    path('doc_work', views.doc_work, name='doc_work'),
    path('deletedoc_work<int:work_id>',views.deletedoc_work,name='deletedoc_work'), 
    path('tableworkdocs<int:uid_9>', views.table_work_docs, name='tableworkdocs'),
    path('emptableworkdocs<int:uid_9>',
         views.emptable_work_docs, name='emptableworkdocs'),
    path('updateworkdocs', views.update_work_docs, name='updateworkdocs'),
    path('empdoc_work', views.empdoc_work, name='empdoc_work'),
    path('edit_doc_work',views.edit_doc_work, name='edit_doc_work'),
    path('edit_empdoc_work', views.edit_empdoc_work, name='edit_empdoc_work'),
    path('deleteempdoc_work/<int:work_id>', views.deleteempdoc_work, name='deleteempdoc_work'), 

    # path('deleteworkdocs<int:uid_9>',views.delete_work_docs,name='deleteworkdocs'),
    path('workweeknav', views.workweek_nav, name='workweeknav'),
    # path('work_week', views.work_week, name='work_week'),

    path('attendance_workweek', views.attendance_workweek,
         name='attendance_workweek'),
    path('add_workweek', views.add_workweek, name='add_workweek'),
    path('edit_workweek', views.edit_workweek, name='edit_workweek'),
    path('delete_workweek/<int:id>/',
         views.delete_workweek, name='delete_workweek'),

    path('assign_workweek', views.view_assignworkweek, name='view_assignworkweek'),
    path('assignworkweek', views.assignworkweek, name='assignworkweek'),
    path('delete_assignworkweek/<int:assign_rule_id>/',
         views.delete_assignworkweek, name='delete_assignworkweek'),

    path('empworkweeknav', views.empworkweek_nav, name='empworkweeknav'),
    path('payrollnav', views.payroll_nav, name='payrollnav'),
    path('emppayrollnav', views.emppayroll_nav, name='emppayrollnav'),
    path('filemanagernav', views.filemanager_nav, name='filemanagernav'),
    path('empfilemanagernav', views.empfilemanager_nav, name='empfilemanagernav'),
    path('tablefilemanager<int:uid_10>',
         views.table_file_manager, name='tablefilemanager'),


    # OVERVIEW
    path('companyprofile', views.overview, name='companyprofile'),
    path('empoverview', views.empoverview, name='empoverview'),
    path('createoverview<int:uid>', views.create_overview, name='createoverview'),
    path('updateoverview', views.update_overview, name='updateoverview'),   
    
    # ADDRESS
    path('Address', views.address, name='address1'),
    path('empaddress1', views.empaddress, name='empaddress1'),
    path('Create-Regoffice', views.create_regoffice, name='createregoffice'),
    path('Update-Regoffice', views.update_regoffice, name='upregoffice'),
    path('Create-Corpoffice', views.create_corpoffice, name='createcorpoffice'),
    path('Update-Corpoffice', views.update_corpoffice, name='upcorpoffice'),
    # POLICIES
    path('policy', views.policy, name='policy1'),
    path('emppolicy', views.emppolicy, name='emppolicy1'),
    path('companypolicy', views.create_companypolicy, name='companypolicy1'),
    path('deletecompanypolicy<int:cid>',
         views.delete_companypolicy, name='deletecompanypolicy'),

    # ATTENDANCE
    path('dailylog', views.daily_log, name='dailylog'),
    # path('empdailylog',views.empdaily_log,name='empdailylog'),
    path('empdailylog', views.empdaily_log, name='empdailylog'),
    path('automationlog', views.automation_log, name='automationlog'),
    path('export-automation-log', views.export_automation_log, name='export-automation-log'),
    path('empautomationlog', views.empautomation_log, name='empautomationlog'),
    #####

    # path('empadmin1',views.empadmin,name='empadmin1'),
    path('pass', views.forgot, name='pass'),
    path('changepass', views.change_password, name='changepass'),
    path("send_otp", views.send_otp, name="send otp"),
    path('logout', views.logout_user, name='logout'),
    path('log', views.log, name='log'),
    path('admin_log', views.admin_log, name='admin_log'),
    path('cancel_adminleave', views.cancel_adminleave, name='cancel_adminleave'),
    path('emplog', views.emplog, name='emplog'),
    path('cancel_empleave', views.cancel_empleave, name='cancel_empleave'),
    path('Rules', views.Rules, name='Rules'),
    path('generalsettings', views.generalsettings, name='generalsettings'),
    path('advancedsettings', views.advancedsettings, name='advancedsettings'),
    path('empRules', views.empRules, name='empRules'),


    # path('advanced',views.advanced,name='advanced'),
    # path('sam',views.sam,name='sam'),
    path('apply', views.apply_leave, name='apply'),
    path('empapply', views.empapply_leave, name='empapply'),
    path('leave', views.leave, name='leave'),
    path('update_leaves', views.update_leaves, name='update_leaves'),
    path('empleave', views.empleave, name='empleave'),
    path('approve_leave', views.approve_leave, name='approve_leave'),
    path('bulk_approve_leave', views.bulk_approve_leave, name='bulk_approve_leave'),
    path('export_leave_data', views.export_leave_data, name='export_leave_data'),
    path('reject_leave', views.reject_leave, name='reject_leave'),
    path('cancel_leave', views.cancel_leave, name='cancel_leave'),

     path('leavebalance', views.leavebalance, name='balance'),
    path('assignleaverule', views.assignleaverule, name='assignrule'),
    path('addassignrule', views.addassignrule, name='addassignrule'),
    path('delete_assign_rule/<int:assign_rule_id>/',
         views.delete_assign_rule, name='delete_assign_rule'),
    # settings
    path('Department', views.department, name='department'),
    path('Add-Department', views.add_department, name='depart1'),
    path('Update-Department', views.update_depart, name='upd'),
    path('delete<int:userid>', views.delete_department, name='del1'),

    

    path('Designation', views.designation, name='designation'),
    path('Add-Designation', views.add_designation, name='desig1'),
    path('Update-Designation', views.update_designation, name='upd1'),
    path('Delete-Designation<int:userid>',
         views.delete_designation, name='delete'),

    path('Subdepartment', views.subdepartment, name='subdepartment'),
    path('Add-Subdepartment', views.add_subdepartment, name='add_subdepartment'),
    path('Update-Subdepartment', views.update_subdepartment, name='sub1'),
    path('Delete-Subdepartment<int:userid>',
         views.delete_subdepartment, name='subdelete'),

    path('Jobtitle', views.job, name='job'),
    path('Add-Jobtitle', views.addjob, name='addjob'),
    path('Update-Jobtitle', views.update_job, name='upd2'),
    path('Delete-Jobtitle<int:userid>', views.delete_job, name='jobdelete'),

    path('Worklocation', views.worklocation, name='wrk'),
    path('Add-Worklocation', views.add_worklocation, name='wrk1'),
    path('Update-Worklocation', views.update_wrklocation, name='upd4'),
    path('Delete-Worklocation<int:userid>',
         views.delete_wrklocation, name='wrkdelete'),

    path('Email', views.emailconfig, name='email'),
    path('Add-Email', views.add_emailconfig, name='addemail'),
    path('update-email', views.update_emailconfig, name='upemail'),
    path('Delete-Email<int:userid>', views.delete_emailconfig, name='demail'),

    path('company-rule', views.rule, name='rule'),
    path('add-rule', views.add_rule, name='addrule'),
    path('update-rule', views.update_rules, name='updrule'),
    path('delete-rule<int:userid>', views.delete_rule, name='delrule'),
    path('Profile', views.view_profile, name='profile'),
    # path('leave_applctn',views.mail,name='mailapplcn'),
    path('help_page', views.help_page, name='help_page'),
    path('attendanceRule', views.attendanceRule, name='attendanceRule'),
    path('add_attendanceRule', views.add_attendanceRule, name='add_attendanceRule'),
    path('edit_attendanceRule', views.edit_attendanceRule,
         name='edit_attendanceRule'),
    path('delete_attendancerule<int:id>',
         views.delete_attendancerule, name='delete_attendancerule'),
    path('view_assignattendancerule', views.view_assignattendancerule,
         name='view_assignattendancerule'),
    path('assignattendancerule', views.assignattendancerule,
         name='assignattendancerule'),
    path('delete_assignattendancerule/<int:assign_rule_id>/',
         views.delete_assignattendancerule, name='delete_assignattendancerule'),
    path('emp-attendanceRule', views.EmpAttendanceRule, name='empattendanceRule'),

    path('view_daily_log<int:id>', views.view_daily_log, name='view_daily_log'),
    path('view_monthly_log<int:id>', views.view_monthly_log, name='view_monthly_log'),

    path('view_automation_log<int:id>',views.view_automation_log, name='view_automation_log'),
    path('view_comp_off<int:id>',views.view_comp_off, name='view_comp_off'),
    path('view_attendance_rule<int:id>',views.view_attendance_rule, name='view_attendance_rule'),

    path('salary_component', views.salary_component, name='salary_component'),
    path('add_salary_component', views.add_salary_component,
         name='add_salary_component'),
    path('update_salary_component', views.update_salary_component,
         name='update_salary_component'),
    path('delete_salary_component<int:userid>',
         views.delete_salary_component, name='delete_salary_component'),


    # path('lemp',views.list_emp,name='emp1')

    # Payroll

    path('pay-slip', views.pay_slip, name='pay_slip'),
    path('download_payslip_pdf', views.download_payslip_pdf, name='download_payslip_pdf'),   
    path('download_emppayslip_pdf', views.download_emppayslip_pdf, name='download_emppayslip_pdf'),   
    path('emppay-slip', views.emppay_slip, name='emppay_slip'),
    path('runpayroll_attendance', views.runpayroll, name='runpayroll'),
#     path('edit_lop', views.edit_lop, name='edit_lop'),
    path('export_runpayroll',views.export_runpayroll,name='export_runpayroll'),
    path('search_runpayroll',views.search_runpayroll,name='search_runpayroll'),
#     path('salary-structure', views.view_salary_structure, name='salarystructure'),
    path('create_salary',views.createsalary,name='create_salary'),
    path('addsalary',views.add_createsalarystructure,name='addsalary'),
    path('edit_salary_structure',views.edit_salary_structure,name='edit_salary_structure'),
    path('delete_salary_structure<int:id>',views.delete_salary_structure, name='delete_salary_structure'),
    path('delete_component_amount<int:structure_id>/<int:name_id>', views.delete_component_amount, name='delete_component_amount'),

    path('view_assign_salarystructure', views.view_assign_salarystructure, name='view_assign_salarystructure'),
    path('assign_salarystructure', views.assign_salarystructure, name='assign_salarystructure'),
    path('delete_assign_salarystructure/<int:assign_rule_id>/', views.delete_assign_salarystructure, name='delete_assign_salarystructure'),
    path('export_salarystructure', views.export_salarystructure, name='export_salarystructure'),
    path('edit_assignsalary', views.edit_assignsalary, name='edit_assignsalary'),

    path('salary_structure', views.salary_structure, name='salary_structure'),
    path('empsalary_structure', views.empsalary_structure,name='empsalary_structure'),

    path('empsalary-structure', views.empview_salary_structure,
         name='empsalarystructure'),
    path('add-salary-structure<int:uid_12>',
         views.add_salary_structure, name='add_salary_structure'),
    path('update-salary-structure', views.update_salary_structure,
         name='update_salary_structure'),
    path('delete-salary-structure<int:myuser_12__id>',
         views.delete_salary_structure, name='delete_salary_structure'),

    path('declaration', views.declaration, name='declaration'),

    path('empdeclaration', views.empdeclaration, name='empdeclaration'),


    path('bank_account', views.bank_account, name='bank_account'),
    path('add_bank-account<int:uid_11>',
         views.add_bank_account, name='add_bank-account'),
    path('bank-account', views.update_bank_account, name='update_bank_account'),
    path('delete_bank-account<int:myuser_11__id>',
         views.delete_bank_account, name='delete_bank-account'),

    path('empbank_account', views.empbank_account, name='empbank_account'),
    path('empadd_bank-account<int:uid_11>',
         views.empadd_bank_account, name='empadd_bank-account'),
    path('empbank-account', views.empupdate_bank_account,
         name='empupdate_bank-account'),
    path('empdelete_bank-account<int:myuser_11__id>',
         views.empdelete_bank_account, name='empdelete_bank-account'),

    path('e_exit', views.e_exit, name='e_exit'),
    path('add_e_exit', views.add_e_exit, name='add_e_exit'),
    path('update_e_exit', views.update_e_exit, name='update_e_exit'),
    path('delete_resignation/<int:id>/',
         views.delete_resignation, name='delete_resignation'),

    path('empe_exit', views.empe_exit, name='empe_exit'),
    path('empadd_e_exit', views.empadd_e_exit, name='empadd_e_exit'),
    path('edit_resignation/<int:resignation_id>/', views.edit_resignation, name='edit_resignation'),
    path('empdelete_resignation/<int:id>/', views.empdelete_resignation, name='empdelete_resignation'),

    path('resignationlist', views.resignationlist, name='resignationlist'),
    path('approve_resignation', views.approve_resignation,
         name='approve_resignation'),
    path('cancel_resignation', views.cancel_resignation, name='cancel_resignation'),
    path('reject_resignation', views.reject_resignation, name='reject_resignation'),

    path('notification', views.notification, name='notification'),
    path('empnotification', views.empnotification, name='empnotification'),
    path('delete_notifications', views.delete_notifications,
         name='delete_notifications'),
    path('delete_empnotifications', views.delete_empnotifications,name='delete_empnotifications'),

     path('attendance_logs', views.attendance_logs, name='attendance_logs'),
     path('new_attendance_logs', views.new_attendance_logs, name='new_attendance_logs'),
     # path('edit_attendance_logs', views.edit_attendance_logs, name='edit_attendance_logs'),
     path('export_attendance_logs', views.export_attendance_logs, name='export_punch_data'),

    # Add the WebSocket URL patterns
    path('ws/', include(websocket_urlpatterns)),

    #admin monthly_log path
    path('monthly_log', views.monthly_log, name='monthly_log'),
    # employee monthly_log path
    path('emp_monthly_log', views.emp_monthly_log, name='emp_monthly_log'),

    ###################################### API VIEWS ##################################
    path('empdaily_log_api', views.empdaily_log_api, name='empdaily_log_api'),
    path('admin_employee_detials', views.admin_employee_detials,
         name='admin_employee_detials'),
    path('employee_details', views.employee_details,
         name='employee_details'),

     # calendar
     path('calendar',views.view_calendar,name='calender'),
     path('emp_calendar',views.view_emp_calendar,name='emp_calender'),

     path('holidayview',views.view_holiday,name='Holidayview'),
     path('addholiday',views.addholiday,name='addholiday'),
     path('editholiday',views.editholiday,name='editholiday'),
     path('deleteholiday_list<int:id>', views.deleteholiday_list, name='deleteholiday_list'),
      path('payroll_declaration', views.payroll_dec, name='payroll_dec'),
     path('reimbursements', views.reimbursements, name='reimbursements'),
     path('add_re', views.empadd_reimbursements, name='add_re'),
     path('app_re', views.approve_reimbursement, name='app_re'),
     path('can_re', views.cancel_reimbursement, name='can_re'),
     path('reject_reimbursement', views.reject_reimbursement, name='reject_reimbursement'),

     #Clock in out uri
     path("clock-in-out", views.clock_in_out, name="clock_in_out"),
     path("runpayroll_leave", views.payroll_leave, name="payroll_leave"),
     path("calculated_salary", views.calculate_salary, name="calculated_salary"),
     path("pay_register", views.pay_register, name="pay_register"),    
     path("payregister_statuschange", views.payregister_statuschange, name="payregister_statuschange"),    
     path("download_payregister", views.download_payregister, name="download_payregister"),    

     path("adhoc_component", views.adhoc_component, name="adhoc_component"),
     path("adhoc_deductions", views.adhoc_deductions, name="adhoc_deductions"),
     path("add_adhocearningcomp", views.add_adhocearningcomp, name="add_adhocearningcomp"),
     path("add_adhocdeductioncomp", views.add_adhocdeductioncomp, name="add_adhocdeductioncomp"),
     path("edit_adhocearningcomp", views.edit_adhocearningcomp, name="edit_adhocearningcomp"),
     path("edit_adhocdeductioncomp", views.edit_adhocdeductioncomp, name="edit_adhocdeductioncomp"),
     path("delete_adhocearningcomp<int:id>", views.delete_adhocearningcomp, name="delete_adhocearningcomp"),
     path("delete_adhocdeductioncomp<int:id>", views.delete_adhocdeductioncomp, name="delete_adhocdeductioncomp"),

     path("adhoc", views.adhoc, name="adhoc"),
     path("create_adhoc", views.create_adhoc, name="create_adhoc"),
     path("edit_adhoc", views.edit_adhoc, name="edit_adhoc"),
     path("delete_adhoc<int:id>", views.delete_adhoc, name="delete_adhoc"),

     path("salary_onhold", views.salary_onhold, name="salary_onhold"),
     path("addsalary_onhold", views.addsalary_onhold, name="addsalary_onhold"),
     path("editsalary_onhold", views.editsalary_onhold, name="editsalary_onhold"),
     
     path("salary_revision", views.salary_revision, name="salary_revision"),

     path("runpayroll_overview", views.runpayroll_overview, name="runpayroll_overview"),
     path("payout", views.payout, name="payout"),
     path('request-approval', views.request_approval, name="request-approval"),
     path('list-request-approvals', views.list_requests, name="list-request-approvals"),
     path('request-approvals', views.list_approvals,
          name="list-approval-request-approvals"),
     path('accept-request-approval', views.accept_request_approval,
          name="accept-request-approval"),
     path('reject-request-approval', views.reject_request_approval,
         name="reject-request-approval"),
     path('list-comp-off', views.list_comp_off , name="list-comp-off"),
     path('emp-list-comp-off', views.emp_list_comp_off , name="emp-list-comp-off"),
     path('export-request-approvals', views.export_approvals_request , name="export-approvals-request"),
     path("export-request-approved-or-rejected" , views.export_request_approved_or_rejected , name = "export-request-approved-or-rejected"),
     path('penalty-log-revert', views.penalty_log_revert, name="penalty-log-revert"),
     path('comp-of-revert', views.comp_off_revert,
          name="comp-off-revert"),
     path('get-work-duration', views.show_work_duration, name="get-work-duration"),

     path('inactive_empdash', views.inactive_empdash, name='inactive_empdash'),
     path('inactive_personalinfo', views.inactive_personalinfo, name='inactive_personalinfo'),
     path('inactive_work', views.inactive_work, name='inactive_work'),
     path('inactive_team', views.inactive_team, name='inactive_team'),
     path('inactive_education', views.inactive_education, name='inactive_education'),
     path('inactive_family', views.inactive_family, name='inactive_family'),
     path('inactive_document', views.inactive_document, name='inactive_document'),
     path('inactive_payroll', views.inactive_payroll, name='inactive_payroll'),
     path('inactive_salarystructure', views.inactive_salarystructure, name='inactive_salarystructure'),
     path('inactive_bankaccount', views.inactive_bankaccount, name='inactive_bankaccount'),
     path('inactive_reimbursements', views.inactive_reimbursements, name='inactive_reimbursements'),
     path('inactive_certifications', views.inactive_certifications, name='inactive_certifications'),
     path('inactive_docwork', views.inactive_docwork, name='inactive_docwork'),
     path('inactive_workweek', views.inactive_workweek, name='inactive_workweek'),
     path('inactive_e_exit', views.inactive_e_exit, name='inactive_e_exit'),
     path('inactive_overview', views.inactive_overview, name='inactive_overview'),
     path('inactive_address', views.inactive_address, name='inactive_address'),
     path('reporting-manager-team-log', views.reporting_manager_team_log, name='reporting_manager_team_log'),
     path('search_punch_logs',views.search_punch_logs,name="search_punch_logs"),
     path('export-punch-logs', views.export_punch_logs, name='export_punch_logs'),
     path('get_usernames', views.get_usernames, name='get_usernames'),

     path('attendance-summary', views.attendance_summary, name='attendance_summary'),
     path('monthly-movements', views.monthly_employee_movements, name='monthly-movements'),


     path('set-home-location', views.set_home_location, name='set_home_location'),
     path('home-locations', views.view_all_home_locations, name='view_all_home_locations'),

     path('view-branches', views.view_branch_locations, name='view_branch_locations'),
     path('add-branch', views.add_branch_location, name='add_branch_location'),
     path('edit-branch/<int:pk>', views.edit_branch_location, name='edit_branch_location'),
     path('delete-branch-location', views.delete_branch_location, name='delete_branch_location'),

     path('employee-profiles/', views.list_employee_profiles, name='list_employee_profiles'),
     path('assign_branch', views.create_employee_profile, name="assign-branch-location"),
     path('delete-employee-profile/', views.delete_employee_profile, name='delete_employee_profile'),

     path('experience_certificates/', views.list_generated_certificates, name='list_generated_certificates'),
     path('view-certificate/<int:employee_id>/', views.admin_view_certificate_pdf, name='admin_view_certificate_pdf'),
     path('toggle_edit_permission/', views.toggle_edit_permission, name='toggle_edit_permission'),

     path('update_resignation_status/<int:resignation_id>/', views.update_resignation_status, name='update_resignation_status'),
     path('update_resignation/<int:resignation_id>/', views.update_resignation_details, name='update_resignation_details'),
          
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
