# Generated by Django 3.1.4 on 2025-06-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payactionstatus',
            name='actiontype',
            field=models.CharField(blank=True, choices=[('On Hold', 'On Hold'), ('Pay', 'Pay')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='payoutstatus',
            name='reason',
            field=models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Pay', 'Pay')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='payoutstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Pay', 'Pay')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emptype',
            field=models.CharField(blank=True, choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Intern', 'Intern'), ('Contract', 'Contract')], max_length=40, null=True),
        ),
    ]
