# Generated by Django 3.1.4 on 2025-06-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20250620_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoc',
            name='cmptype',
            field=models.CharField(blank=True, choices=[('Deduction', 'Contract'), ('Earning', 'Earning')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='payactionstatus',
            name='actiontype',
            field=models.CharField(blank=True, choices=[('Pay', 'Pay'), ('On Hold', 'On Hold')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='payoutstatus',
            name='reason',
            field=models.CharField(blank=True, choices=[('Pay', 'Pay'), ('Unpaid', 'Unpaid')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='payoutstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('Pay', 'Pay'), ('Unpaid', 'Unpaid')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reportingmanager',
            name='type',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emptype',
            field=models.CharField(blank=True, choices=[('Part Time', 'Part Time'), ('Intern', 'Intern'), ('Contract', 'Contract'), ('Full Time', 'Full Time')], max_length=40, null=True),
        ),
    ]
