# Generated by Django 3.1.4 on 2025-06-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20250620_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='Appliedon',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportingmanager',
            name='type',
            field=models.CharField(blank=True, choices=[('Secondary', 'Secondary'), ('Primary', 'Primary')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emptype',
            field=models.CharField(blank=True, choices=[('Contract', 'Contract'), ('Full Time', 'Full Time'), ('Intern', 'Intern'), ('Part Time', 'Part Time')], max_length=40, null=True),
        ),
    ]
