# Generated by Django 3.1.4 on 2025-06-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20250621_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhoc',
            name='cmptype',
            field=models.CharField(blank=True, choices=[('Earning', 'Earning'), ('Deduction', 'Contract')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='payactionstatus',
            name='actiontype',
            field=models.CharField(blank=True, choices=[('On Hold', 'On Hold'), ('Pay', 'Pay')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reportingmanager',
            name='type',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emptype',
            field=models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Contract', 'Contract'), ('Full Time', 'Full Time'), ('Part Time', 'Part Time')], max_length=40, null=True),
        ),
    ]
