# Generated by Django 3.1.4 on 2025-06-28 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20250622_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBranchLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=15)),
                ('lon', models.DecimalField(decimal_places=8, max_digits=15)),
                ('radius', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='adhoc',
            name='cmptype',
            field=models.CharField(blank=True, choices=[('Deduction', 'Contract'), ('Earning', 'Earning')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='payactionstatus',
            name='actiontype',
            field=models.CharField(blank=True, choices=[('Pay', 'Pay'), ('On Hold', 'On Hold')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reportingmanager',
            name='type',
            field=models.CharField(blank=True, choices=[('Secondary', 'Secondary'), ('Primary', 'Primary')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emptype',
            field=models.CharField(blank=True, choices=[('Contract', 'Contract'), ('Part Time', 'Part Time'), ('Intern', 'Intern'), ('Full Time', 'Full Time')], max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_edit_requested', models.BooleanField(default=False)),
                ('branch_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='app1.companybranchlocation')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'Employee'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeGeoFence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('home_lon', models.DecimalField(decimal_places=8, max_digits=11)),
                ('home_radius', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
