# Generated by Django 3.1.4 on 2025-06-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20250628_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeegeofence',
            name='home_lat',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='payactionstatus',
            name='actiontype',
            field=models.CharField(blank=True, choices=[('On Hold', 'On Hold'), ('Pay', 'Pay')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='reportingmanager',
            name='type',
            field=models.CharField(blank=True, choices=[('Primary', 'Primary'), ('Secondary', 'Secondary')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emptype',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Contract', 'Contract'), ('Part Time', 'Part Time'), ('Intern', 'Intern')], max_length=40, null=True),
        ),
    ]
