# Generated by Django 3.1.4 on 2025-07-06 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20250628_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationform',
            name='actual_last_working_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationform',
            name='allow_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resignationform',
            name='update_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payoutstatus',
            name='reason',
            field=models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Pay', 'Pay')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='payoutstatus',
            name='status',
            field=models.CharField(blank=True, choices=[('Unpaid', 'Unpaid'), ('Pay', 'Pay')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='resignationform',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Updated', 'Updated')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emptype',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Intern', 'Intern'), ('Part Time', 'Part Time'), ('Contract', 'Contract')], max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='ExperienceCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_file', models.FileField(upload_to='experience_certificates/')),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('resignation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.resignationform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CertificateDownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, default='12.0.0.1', null=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.experiencecertificate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
